services:
  ubuntu-dev:
    build: .
    container_name: ubuntu-dev
    hostname: ubuntu-dev
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - E:/Projects:/projects
      - D:/Shared:/shared
    tty: true
    stdin_open: true
